include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - lib/generated/*.dart
    - lib/generated/intl/*.dart
    - lib/**/*.g.dart

linter:
  rules:
    unnecessary_brace_in_string_interps: false
    avoid_classes_with_only_static_members: false
    sort_pub_dependencies: false

